=== yoshinababan/Tugas-Web-Service-Yoshi/loginjasahotel.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT loginjasahotel (resepsionis,OfficeBoy,Manager,satpam,Pemesan)>
<!ATTLIST loginjasahotel
    xmlns CDATA #FIXED ''>

<!ELEMENT resepsionis (namaresepsionis,tandapengenal,nik,alamat,jeniskelamin,
                       agama,pekerjaan,tempatlahir,kewarganegaraan,tahunkerja)>
<!ATTLIST resepsionis
    xmlns CDATA #FIXED ''>

<!ELEMENT OfficeBoy (namaOB,alamat,Kontak,jeniskelamin,agama,pekerjaan,
                     tempatlahir,email,tahunkerja,jabatan)>
<!ATTLIST OfficeBoy
    xmlns CDATA #FIXED ''>

<!ELEMENT Manager (namaManager,asal,Kontak,jeniskelamin,agama,pekerjaan,
                   tempatlahir,email,hobbi,jabatan)>
<!ATTLIST Manager
    xmlns CDATA #FIXED ''>

<!ELEMENT satpam (namasatpam,alamat,kontak,jeniskelamin,agama,pekerjaan,
                  tempatlahir,email,umur,jabatan)>
<!ATTLIST satpam
    xmlns CDATA #FIXED ''>

<!ELEMENT Pemesan (namapemesan,alamat,nohp,jeniskelamin,agama,Status,
                   tempatlahir,email,kegiatan,nim)>
<!ATTLIST Pemesan
    xmlns CDATA #FIXED ''>

<!ELEMENT namaresepsionis (#PCDATA)>
<!ATTLIST namaresepsionis
    xmlns CDATA #FIXED ''>

<!ELEMENT tandapengenal (#PCDATA)>
<!ATTLIST tandapengenal
    xmlns CDATA #FIXED ''>

<!ELEMENT nik (#PCDATA)>
<!ATTLIST nik
    xmlns CDATA #FIXED ''>

<!ELEMENT kewarganegaraan (#PCDATA)>
<!ATTLIST kewarganegaraan
    xmlns CDATA #FIXED ''>

<!ELEMENT namaOB (#PCDATA)>
<!ATTLIST namaOB
    xmlns CDATA #FIXED ''>

<!ELEMENT namaManager (#PCDATA)>
<!ATTLIST namaManager
    xmlns CDATA #FIXED ''>

<!ELEMENT asal (#PCDATA)>
<!ATTLIST asal
    xmlns CDATA #FIXED ''>

<!ELEMENT hobbi (#PCDATA)>
<!ATTLIST hobbi
    xmlns CDATA #FIXED ''>

<!ELEMENT namasatpam (#PCDATA)>
<!ATTLIST namasatpam
    xmlns CDATA #FIXED ''>

<!ELEMENT kontak (#PCDATA)>
<!ATTLIST kontak
    xmlns CDATA #FIXED ''>

<!ELEMENT umur (#PCDATA)>
<!ATTLIST umur
    xmlns CDATA #FIXED ''>

<!ELEMENT namapemesan (#PCDATA)>
<!ATTLIST namapemesan
    xmlns CDATA #FIXED ''>

<!ELEMENT nohp (#PCDATA)>
<!ATTLIST nohp
    xmlns CDATA #FIXED ''>

<!ELEMENT Status (#PCDATA)>
<!ATTLIST Status
    xmlns CDATA #FIXED ''>

<!ELEMENT kegiatan (#PCDATA)>
<!ATTLIST kegiatan
    xmlns CDATA #FIXED ''>

<!ELEMENT nim (#PCDATA)>
<!ATTLIST nim
    xmlns CDATA #FIXED ''>

<!ELEMENT alamat (#PCDATA)>
<!ATTLIST alamat
    xmlns CDATA #FIXED ''>

<!ELEMENT jeniskelamin (#PCDATA)>
<!ATTLIST jeniskelamin
    xmlns CDATA #FIXED ''>

<!ELEMENT agama (#PCDATA)>
<!ATTLIST agama
    xmlns CDATA #FIXED ''>

<!ELEMENT pekerjaan (#PCDATA)>
<!ATTLIST pekerjaan
    xmlns CDATA #FIXED ''>

<!ELEMENT tempatlahir (#PCDATA)>
<!ATTLIST tempatlahir
    xmlns CDATA #FIXED ''>

<!ELEMENT tahunkerja (#PCDATA)>
<!ATTLIST tahunkerja
    xmlns CDATA #FIXED ''>

<!ELEMENT Kontak (#PCDATA)>
<!ATTLIST Kontak
    xmlns CDATA #FIXED ''>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email
    xmlns CDATA #FIXED ''>

<!ELEMENT jabatan (#PCDATA)>
<!ATTLIST jabatan
    xmlns CDATA #FIXED ''>

=== yoshinababan/Tugas-Web-Service-Yoshi/loginjasahotel.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE loginjasahotel SYSTEM "loginjasahotel.dtd">
<loginjasahotel>
	<resepsionis>
		<namaresepsionis>Supratman</namaresepsionis>
		<tandapengenal>Nama Resepsionis</tandapengenal>
		<nik>1154125</nik>
		<alamat>Sarijadi</alamat>
		<jeniskelamin>Laki-Laki</jeniskelamin>
		<agama>Islam</agama>
		<pekerjaan>resepsionis hotel</pekerjaan>
		<tempatlahir>bandung</tempatlahir>
		<kewarganegaraan>Indonesia</kewarganegaraan>
		<tahunkerja>2012</tahunkerja>
	</resepsionis>
	
	<OfficeBoy>
		<namaOB>Katimin</namaOB>
		<alamat>Soekarno Hatta</alamat>
		<Kontak>081250041000</Kontak>
		<jeniskelamin>Laki-Laki</jeniskelamin>
		<agama>Islam</agama>
		<pekerjaan>Office Boy Jasa hotel</pekerjaan>
		<tempatlahir>Soreang</tempatlahir>
		<email>Katimin31@gmail.com</email>
		<tahunkerja>2009</tahunkerja>
		<jabatan>Kepala Office Boy</jabatan>
	</OfficeBoy>
	
	<Manager>
		<namaManager>Yoshi Ricowandi Nababan</namaManager>
		<asal>Medan</asal>
		<Kontak>082165422560</Kontak>
		<jeniskelamin>laki-laki</jeniskelamin>
		<agama>Kristen</agama>
		<pekerjaan>Manager Jasa Hotel</pekerjaan>
		<tempatlahir>Tarutung</tempatlahir>
		<email>Yoshinababan.33@gmail.com</email>
		<hobbi>Futsal dan Sepakbola </hobbi>
		<jabatan>Manager</jabatan>
	</Manager>
	
	<satpam>
		<namasatpam>Raya</namasatpam>
		<alamat>Ciwaruga</alamat>
		<kontak>082212112121</kontak>
		<jeniskelamin>Laki-Laki</jeniskelamin>
		<agama>Hindu</agama>
		<pekerjaan>satpam</pekerjaan>
		<tempatlahir>Surabaya</tempatlahir>
		<email>rayasemesta@gmail.com</email>
		<umur> 29 tahun </umur>
		<jabatan>satpam</jabatan>
	</satpam>
	
	<Pemesan>
		<namapemesan>jakirik</namapemesan>
		<alamat>Sipiongot</alamat>
		<nohp>082165422670</nohp>
		<jeniskelamin>Laki-Laki</jeniskelamin>
		<agama>Budha</agama>
		<Status>mahasiswa</Status>
		<tempatlahir>bandung</tempatlahir>
		<email>jakiriksi71@gmail.com</email>
		<kegiatan>Bermain Badminton</kegiatan>
		<nim>1154125</nim>
	</Pemesan>
</loginjasahotel>
